// Package migrate turns the registered Records into versioned migration files,
// applies the ones a database has not seen, and reports drift between the two.
//
// Migrations are forward-only and immutable: once a file is committed it is
// never edited, and a change to a Record produces a NEW file. Applied versions
// are tracked in the schema_migrations table, keyed by version with the file's
// checksum recorded alongside, so an edited-after-apply file is caught.
package migrate

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/michaeltabet/ingest/internal/ledger"
)

// TrackingDDL creates the table that records what has been applied.
const TrackingDDL = `CREATE TABLE IF NOT EXISTS schema_migrations (
  version String,
  checksum String,
  applied_at DateTime64(3) DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(applied_at)
ORDER BY (version);`

var filePattern = regexp.MustCompile(`^(\d{4})_([a-z0-9_]+)\.sql$`)

// Migration is one committed file on disk.
type Migration struct {
	Version  string // the 4-digit prefix, e.g. "0001"
	Name     string // the slug after the prefix
	Path     string
	SQL      string
	Checksum string
}

func checksum(sql string) string {
	sum := sha256.Sum256([]byte(sql))
	return hex.EncodeToString(sum[:])
}

// Load reads every migration file in dir, ordered by version.
func Load(dir string) ([]Migration, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var out []Migration
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		m := filePattern.FindStringSubmatch(e.Name())
		if m == nil {
			if strings.HasSuffix(e.Name(), ".sql") {
				return nil, fmt.Errorf("%s: name must be NNNN_slug.sql", e.Name())
			}
			continue
		}
		path := filepath.Join(dir, e.Name())
		body, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		sql := string(body)
		out = append(out, Migration{
			Version:  m[1],
			Name:     m[2],
			Path:     path,
			SQL:      sql,
			Checksum: checksum(sql),
		})
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Version < out[j].Version })
	return out, nil
}

// Pending renders the DDL for every registered Record that no committed
// migration already creates, in registration order. It is what both Emit and
// Check are built on, so the two can never disagree.
func Pending(dir string) ([]ledger.Record, error) {
	existing, err := Load(dir)
	if err != nil {
		return nil, err
	}

	created := map[string]bool{}
	for _, m := range existing {
		for _, table := range tablesIn(m.SQL) {
			created[table] = true
		}
	}

	var pending []ledger.Record
	for _, r := range ledger.All() {
		if !created[r.Table] {
			pending = append(pending, r)
		}
	}
	return pending, nil
}

var createPattern = regexp.MustCompile(`(?i)CREATE TABLE(?:\s+IF NOT EXISTS)?\s+([a-zA-Z0-9_.]+)`)

func tablesIn(sql string) []string {
	var out []string
	for _, m := range createPattern.FindAllStringSubmatch(sql, -1) {
		out = append(out, m[1])
	}
	return out
}

// Emit writes one migration file containing the DDL for every pending Record.
// It returns the path written, or "" when the schema is already current.
func Emit(dir, name string) (string, error) {
	pending, err := Pending(dir)
	if err != nil {
		return "", err
	}
	if len(pending) == 0 {
		return "", nil
	}

	existing, err := Load(dir)
	if err != nil {
		return "", err
	}
	next := fmt.Sprintf("%04d", len(existing)+1)

	var b strings.Builder
	fmt.Fprintf(&b, "-- %s_%s.sql — generated by cmd/chmigrate from internal/ledger.\n", next, name)
	b.WriteString("-- Do not edit: change the Record and emit a new migration.\n\n")
	for i, r := range pending {
		ddl, err := r.DDL()
		if err != nil {
			return "", err
		}
		if i > 0 {
			b.WriteString("\n\n")
		}
		b.WriteString(ddl)
	}
	b.WriteString("\n")

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, fmt.Sprintf("%s_%s.sql", next, name))
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// DB is the slice of a ClickHouse connection the migrator needs.
type DB interface {
	Exec(ctx context.Context, query string, args ...any) error
	Select(ctx context.Context, dest any, query string, args ...any) error
}

type appliedRow struct {
	Version  string `ch:"version"`
	Checksum string `ch:"checksum"`
}

// Apply runs every migration the database has not recorded, in version order,
// and refuses to proceed if a file was edited after it was applied.
func Apply(ctx context.Context, db DB, dir string) ([]string, error) {
	if err := db.Exec(ctx, TrackingDDL); err != nil {
		return nil, fmt.Errorf("creating schema_migrations: %w", err)
	}

	files, err := Load(dir)
	if err != nil {
		return nil, err
	}

	var rows []appliedRow
	if err := db.Select(ctx, &rows, "SELECT version, checksum FROM schema_migrations FINAL"); err != nil {
		return nil, fmt.Errorf("reading schema_migrations: %w", err)
	}
	applied := map[string]string{}
	for _, r := range rows {
		applied[r.Version] = r.Checksum
	}

	var ran []string
	for _, m := range files {
		if got, seen := applied[m.Version]; seen {
			if got != m.Checksum {
				return ran, fmt.Errorf("%s was edited after it was applied "+
					"(recorded %s, file %s) — migrations are immutable; emit a new one",
					filepath.Base(m.Path), got[:12], m.Checksum[:12])
			}
			continue
		}

		for _, stmt := range statements(m.SQL) {
			if err := db.Exec(ctx, stmt); err != nil {
				return ran, fmt.Errorf("%s: %w", filepath.Base(m.Path), err)
			}
		}
		if err := db.Exec(ctx,
			"INSERT INTO schema_migrations (version, checksum) VALUES (?, ?)",
			m.Version, m.Checksum); err != nil {
			return ran, fmt.Errorf("recording %s: %w", filepath.Base(m.Path), err)
		}
		ran = append(ran, filepath.Base(m.Path))
	}
	return ran, nil
}

// statements splits a migration file into individual statements. ClickHouse
// accepts one statement per call, and comment lines are dropped so a trailing
// comment never becomes an empty statement.
func statements(sql string) []string {
	var out []string
	for _, part := range strings.Split(sql, ";") {
		var lines []string
		for _, line := range strings.Split(part, "\n") {
			if strings.HasPrefix(strings.TrimSpace(line), "--") {
				continue
			}
			lines = append(lines, line)
		}
		stmt := strings.TrimSpace(strings.Join(lines, "\n"))
		if stmt != "" {
			out = append(out, stmt)
		}
	}
	return out
}
