-- 0001_ledger_baseline.sql — generated by cmd/chmigrate from internal/ledger.
-- Do not edit: change the Record and emit a new migration.

CREATE TABLE IF NOT EXISTS test_campaign (
  campaign String,
  platform LowCardinality(String),
  key String,
  rung UInt16,
  passed UInt8,
  evidence_outcome LowCardinality(String),
  data_errors Array(String),
  params String,
  run_at DateTime64(3)
)
ENGINE = MergeTree
ORDER BY (platform, run_at);

CREATE TABLE IF NOT EXISTS calibration_observations (
  platform LowCardinality(String),
  window_closed UInt32,
  sources_measured UInt32,
  avg_seconds Float64,
  ok_rate Float64,
  recommend_batch UInt16,
  note String,
  run_at DateTime64(3)
)
ENGINE = MergeTree
ORDER BY (platform, run_at);
